services:

  react_native_app:
    build:
      context: ./Frontend/
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
      - '8081:8081'
    volumes:
      - ./Frontend:/opt/react_native_app:delegated
      - notused:/opt/react_native_app/node_modules
    working_dir: /opt/react_native_app
    entrypoint: ["/bin/sh", "-c"]
    command:
    - |
      npm install && npx expo start --tunnel
    healthcheck:
      disable: true

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27070:27017

  eureka-server:
    build: Backend/eureka-server/
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8761/actuator/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

  api-gateway:
    build: Backend/api-gateway/
    depends_on:
      eureka-server:
        condition: service_healthy
        restart: true
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_SERVICE_URL: ${AUTHENTICATION_SERVICE_URL}
      LOGGING_SERVICE_URL: ${LOGGING_SERVICE_URL}
      NOTIFICATION_SERVICE_URL: ${NOTIFICATION_SERVICE_URL}
      REMINDER_SERVICE_URL: ${REMINDER_SERVICE_URL}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      JWT_SECRET: ${JWT_SECRET}
      IP_ADDRESS: ${IP_ADDRESS}

  authentication-service:
    build: Backend/AuthenticationService/
    depends_on:
      eureka-server:
        condition: service_healthy
        restart: true
    ports:
      - "8082:8082"
    environment:
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

  notification-service:
    build: Backend/NotificationService/
    depends_on:
      eureka-server:
        condition: service_healthy
        restart: true
    ports:
      - "8084:8084"
    environment:
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_APPLICATION_NAME: NotificationService

  reminder-service:
    build: Backend/ReminderService/
    depends_on:
      eureka-server:
        condition: service_healthy
        restart: true
    ports:
      - "8085:8085"
    environment:
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      NOTIFICATION_SERVICE_URL: ${NOTIFICATION_SERVICE_URL}

volumes:
  notused: