spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:eureka-server}
  client:
    register-with-eureka: false
    fetch-registry: false
  service-url:
    defaultZone: https://eureka-server-181273673095.europe-west1.run.app

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


server:
  port: 8761