spring:
  application:
    name: api-gateway

server:
  port: 8080

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-181273673095.asia-south1.run.app/eureka