name: Docker Image CI

on:
  push:
    branches:
        - "*"
  pull_request:
    branches:
        - "*"

jobs:
  build-authentication-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          cd Backend/AuthenticationService
          ./mvnw package
          docker build -t reminder/authentication-service:latest .

