name: Push to Docker Hub CI

on:
  push:
    branches: ["main"]

jobs:

  push-authentication-service:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Package with Maven
        run: |
          cd ./Backend/AuthenticationService
          ./mvnw clean package

      - name: Build & push AuthenticationService
        uses: docker/build-push-action@v6
        with:
          context: ./Backend/AuthenticationService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/authentication-service:latest

  push-logging-service:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}   
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3   

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Package with Maven
        run: |
          cd ./Backend/LoggingService
          ./mvnw clean package

      - name: Build & push LoggingService
        uses: docker/build-push-action@v6
        with:
          context: ./Backend/LoggingService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/logging-service:latest

  push-notification-service:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}   
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Package with Maven
        run: |
          cd ./Backend/NotificationService
          ./mvnw clean package
        
      - name: Build & push NotificationService
        uses: docker/build-push-action@v6
        with:
          context: ./Backend/NotificationService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/notification-service:latest

  push-reminder-service:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}   
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3   

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Package with Maven
        run: |
          cd ./Backend/ReminderService
          ./mvnw clean package

      - name: Build & push ReminderService
        uses: docker/build-push-action@v6
        with:
          context: ./Backend/ReminderService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/reminder-service:latest
