name: Push to Docker Hub CI

on:
  workflow_run:
    workflows: [build-docker]
    types:
    - completed

jobs:

  push-authentication-service:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push AuthenticationService
        uses: docker/build-push-action@v6
        with:
          context: ./Backend/AuthenticationService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: reminder/authentication-service:latest

  push-logging-service:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3   
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3   
      - name: Build & push LoggingService
        uses: docker/build-push-action@v6
        with:
          context: ./Backend/LoggingService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: reminder/logging-service:latest

  push-notification-service:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3   
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3   
      - name: Build & push NotificationService
        uses: docker/build-push-action@v6
        with:
          context: ./Backend/NotificationService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: reminder/notification-service:latest

  push-reminder-service:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3   
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3   
      - name: Build & push ReminderService
        uses: docker/build-push-action@v6
        with:
          context: ./Backend/ReminderService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: reminder/reminder-service:latest
